"""empty message

Revision ID: d46d50df087d
Revises: 3ff3b146fbd8
Create Date: 2020-12-08 13:44:36.992447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46d50df087d'
down_revision = '3ff3b146fbd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_factors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_col_1', sa.Numeric(precision=12, scale=4), nullable=True))
        batch_op.add_column(sa.Column('num_col_2', sa.Numeric(precision=12, scale=4), nullable=True))
        batch_op.add_column(sa.Column('num_col_3', sa.Numeric(precision=12, scale=4), nullable=True))
        batch_op.add_column(sa.Column('str_col_1', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('str_col_2', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('str_col_3', sa.String(length=20), nullable=True))
        batch_op.drop_column('col_3')
        batch_op.drop_column('col_2')
        batch_op.drop_column('col_5')
        batch_op.drop_column('col_1')
        batch_op.drop_column('col_4')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_factors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('col_4', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('col_1', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('col_5', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('col_2', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('col_3', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('str_col_3')
        batch_op.drop_column('str_col_2')
        batch_op.drop_column('str_col_1')
        batch_op.drop_column('num_col_3')
        batch_op.drop_column('num_col_2')
        batch_op.drop_column('num_col_1')

    # ### end Alembic commands ###
