"""empty message

Revision ID: 9611191a3d83
Revises: bc2eee4d0747
Create Date: 2021-02-21 21:28:01.275643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9611191a3d83'
down_revision = 'bc2eee4d0747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_loop_rating_step_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_rate_loop_rating_steps', 'rating_steps', ['rate_loop_rating_step_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_steps', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rate_loop_rating_steps', type='foreignkey')
        batch_op.drop_column('rate_loop_rating_step_id')

    # ### end Alembic commands ###
