"""empty message

Revision ID: bc2eee4d0747
Revises: d46d50df087d
Create Date: 2020-12-28 16:14:52.290089

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bc2eee4d0747'
down_revision = 'd46d50df087d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_variables',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('rating_manual_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(length=50), nullable=True),
                    sa.Column('description', sa.String(length=255), nullable=True),
                    sa.Column('variable_type', sa.String(length=10), nullable=True),
                    sa.Column('is_input', sa.Boolean(), nullable=True),
                    sa.Column('is_required', sa.Boolean(), nullable=True),
                    sa.Column('default', sa.String(length=25), nullable=True),
                    sa.Column('constraints', sa.String(length=255), nullable=True),
                    sa.Column('length', sa.String(length=10), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['rating_manual_id'], ['rating_manuals.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating_variables')
    # ### end Alembic commands ###
