"""empty message

Revision ID: c0082e50e8e9
Revises: 2090c7a5c43d
Create Date: 2020-11-23 16:24:14.713588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0082e50e8e9'
down_revision = '2090c7a5c43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_step_parameters', sa.Column('parameter_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating_step_parameters', 'parameter_type')
    # ### end Alembic commands ###
