"""empty message

Revision ID: 34d99c094b7a
Revises: c0082e50e8e9
Create Date: 2020-11-24 16:24:42.127377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d99c094b7a'
down_revision = 'c0082e50e8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('col_1', sa.String(length=20), nullable=True),
    sa.Column('col_2', sa.String(length=20), nullable=True),
    sa.Column('col_3', sa.String(length=20), nullable=True),
    sa.Column('col_4', sa.String(length=20), nullable=True),
    sa.Column('col_5', sa.String(length=20), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating_factors')
    # ### end Alembic commands ###
